name: Security

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  gitleaks:
    uses: netresearch/.github/.github/workflows/gitleaks.yml@main
    secrets:
      GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}

  dependency-review:
    if: github.event_name == 'pull_request'
    uses: netresearch/.github/.github/workflows/dependency-review.yml@main
    permissions:
      contents: read
      pull-requests: write

  composer-audit:
    uses: netresearch/typo3-ci-workflows/.github/workflows/security.yml@main
    with:
      skip-composer-audit: true

  magento-composer-audit:
    uses: netresearch/magento-ci-workflows/.github/workflows/composer-audit.yml@v0.1.1
    secrets:
      MAGENTO_REPO_USERNAME: ${{ secrets.MAGENTO_REPO_USERNAME }}
      MAGENTO_REPO_PASSWORD: ${{ secrets.MAGENTO_REPO_PASSWORD }}
